services:
  app:
    restart: unless-stopped
    volumes:
      - app_code:/var/www                                       # ← código compartido
      - app_storage:/var/www/storage                            # storage persistente
      - ./.env:/var/www/.env
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:ro
    depends_on:
      db:
        condition: service_healthy

  nginx:
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - app_code:/var/www:ro                                    # ← mismo código que app
      - app_storage:/var/www/storage:ro                         # ← mismo storage
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro

  db:
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - jaguelapp

volumes:
  app_code:
  app_storage: