services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    env_file:
      - .env
    networks:
      - jaguelapp
    depends_on:
      db:
        condition: service_started

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    env_file:
      - .env
    command: php artisan queue:work --tries=3 --sleep=3 --max-time=3600
    networks:
      - jaguelapp
    depends_on:
      db:
        condition: service_started
      app:
        condition: service_started

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - jaguelapp
    depends_on:
      - app

  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - jaguelapp

volumes:
  mysql-data:

networks:
  jaguelapp:
    driver: bridge
