services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - jaguelapp
    depends_on:
      db : 
        condition: service_started
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - jaguelapp
    depends_on:
      - app
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - jaguelapp
  
volumes:
    mysql-data:

networks:
  jaguelapp:
    driver: bridge
